#******************************************************************
#
# Copyright 2016 Intel Corporation All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')
Import('iotivity_resource_inc_paths')

if env['TARGET_OS'] == 'linux':
    oic_libs = ['octbstack', 'connectivity_abstraction', 'coap']

    env_octest = env.Clone()
    env_octest.AppendUnique(CPPPATH = ['${IOTIVITY_BASE}/resource/csdk/stack/include/internal'])
    env_octest.AppendUnique(LIBS = [oic_libs])
    test_bins = [
        env_octest.Program('occlient', ['occlient.cpp',
                                        '${IOTIVITY_BASE}/extlibs/cjson/cJSON.c',
                                        '${IOTIVITY_BASE}/extlibs/tinycbor/tinycbor/src/cbortojson.c',
                                        '${IOTIVITY_BASE}/extlibs/tinycbor/tinycbor/src/cborpretty.c'])]

    env.Install('#/${BUILD_DIR}/bin', test_bins)
