#******************************************************************
#
# Copyright 2017 Intel Corporation All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')

alljoyn_libs = ['alljoyn', 'ajrouter']

if env['TARGET_OS'] == 'linux':
    env_unittest = env.Clone();
    env_unittest.VariantDir('examples', '../examples')
    env_unittest.VariantDir('src', '../src')
    unittest_cpp = ['AllJoynBridgeTest.cpp',
                    'examples/Log.cpp',
                    'src/AboutData.cpp',
                    'src/DeviceConfigurationResource.cpp',
                    'src/DeviceResource.cpp',
                    'src/Hash.cpp',
                    'src/Name.cpp',
                    'src/Payload.cpp',
                    'src/PlatformConfigurationResource.cpp',
                    'src/PlatformResource.cpp',
                    'src/Signature.cpp',
                    '${IOTIVITY_BASE}/extlibs/gtest/gtest-1.7.0/lib/.libs/libgtest.a',
                    '${IOTIVITY_BASE}/extlibs/gtest/gtest-1.7.0/lib/.libs/libgtest_main.a']
    env_unittest.AppendUnique(CPPPATH = ['${IOTIVITY_BASE}/extlibs/gtest/gtest-1.7.0/include', '#/src'])
    env_unittest.AppendUnique(LIBS = [
        'crypto',
        alljoyn_libs,
        'cjson',
        'octbstack',
        'connectivity_abstraction',
        'c_common',
        'coap',
        'resource_directory',
        ])
    unittest_bins = env_unittest.Program('AllJoynBridgeTest', unittest_cpp)
    env.Install('#/${BUILD_DIR}/bin', unittest_bins)
