#******************************************************************
#
# Copyright 2016 Intel Corporation All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')
Import('iotivity_resource_inc_paths')
Import('alljoynplugin_lib')

alljoyn_libs = ['alljoyn', 'ajrouter']
oic_libs = ['cjson', 'octbstack', 'connectivity_abstraction', 'c_common', 'coap', 'resource_directory']

env_bridge = env.Clone()
bridge_cpp = ['Plugin.cpp',
              'AllJoynBridge.cpp']
manager_cpp = ['PluginManager.cpp']
env_bridge.AppendUnique(LIBS = [alljoynplugin_lib])
if env['TARGET_OS'] == 'linux':
    env_bridge.AppendUnique(LIBS = ['crypto', alljoyn_libs, oic_libs])
elif env['TARGET_OS'] == 'windows':
    env_bridge.AppendUnique(LIBS = ['win_helper', alljoyn_libs, oic_libs, 'sqlite3'])

examples_bins = [env_bridge.Program('AllJoynBridge', bridge_cpp)]
if env['TARGET_OS'] == 'linux':
    examples_bins += [env_bridge.Program('PluginManager', manager_cpp)]

env.Install('#/${BUILD_DIR}/bin', examples_bins)
